---
# tasks file for update_directory
- hosts : all
  tasks:
    - apt:
        update_cache: yes
        pkg:
          - vim
          - git
          - tree
          - htop
          - curl
          - emacs
          - net-tools
          - sudo
          - make
          - unzip
          - python3
          - python3-pip
